// src/renderer/containers/About.tsx
import { remote } from 'electron';
import * as React from 'react';
import { RouteComponentProps } from 'react-router-dom';

export default class About extends React.Component<RouteComponentProps<{}>, {}> {
  constructor(props: any) {
    super(props);
  }

  public render() {
    return (
      <div>
        <h1>About RareInk</h1>
        <p>Version {remote.app.getVersion()}.</p>
      </div>
    );
  }
}

// src/app/about/about.component.ts
import { Component, OnInit } from '@angular/core';
import { NgxElectronService } from '../core/ngx-electron';

@Component({
  selector: 'rareink-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss']
})
export class AboutComponent implements OnInit {

  public appVersion: string;

  constructor(private electron: NgxElectronService) {
    if (this.electron.isElectron) {
      this.appVersion = this.electron.remote.app.getVersion();
    }
  }

  ngOnInit() {
  }

}

<div class="about">
  <a routerLink="/">Back to home</a>
  <h1>About RareInk</h1>
  <p>Version: {{appVersion}}</p>
</div>
